name: ci-golang-workflow # Nome do workflow
on: 
  pull_request:
    branches:
      - develop

strategy:
  matrix:
    go: ['1.14', '1.24.2']
jobs:
  check-application: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run main.go
